[package]
name = "otr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
ffmpeg-the-third = "1.2.2+ffmpeg-6.0"
tokio = { version = "1.29.1", features = ["full"] }
